In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr
import netCDF4 as nc

In [4]:
# dataset_old = nc.Dataset(r'K:\data\DataUpdate_02_2024\xr_dataread.nc')
dataset_old = xr.open_dataset(r'K:\data\DataUpdate_02_2024\xr_dataread_oldrunning.nc')
dataset_new = xr.open_dataset(r'K:\data\DataUpdate_02_2024\xr_dataread.nc')

In [5]:
dataset_old

<xarray.Dataset>
Dimensions:            (Scenario: 5, Region: 207, Time: 251, Conditionality: 3,
                        Hot_air: 2, Ambition: 2, Temperature: 10, Risk: 5,
                        NonCO2red: 5, NegEmis: 7, Timing: 2)
Coordinates: (12/14)
  * Scenario           (Scenario) object 'SSP1' 'SSP2' 'SSP3' 'SSP4' 'SSP5'
  * Region             (Region) object 'AFG' 'ALB' ... 'Umbrella'
  * Time               (Time) int32 1850 1851 1852 1853 ... 2097 2098 2099 2100
  * Conditionality     (Conditionality) object 'conditional' ... 'unconditional'
  * Hot_air            (Hot_air) object 'include' 'exclude'
  * Ambition           (Ambition) object 'low' 'high'
    ...                 ...
  * NonCO2red          (NonCO2red) float64 0.1 0.33 0.5 0.67 0.9
  * NegEmis            (NegEmis) float64 0.2 0.3 0.4 0.5 0.6 0.7 0.8
  * Timing             (Timing) object 'Delayed' 'Immediate'
    source             object ...
    Version            object ...
    variable           object ...
Data variables: (12/15)
    GDP                (Scenario, Region, Time) float64 ...
    Population         (Scenario, Region, Time) float64 ...
    GHG_hist           (Time, Region) float64 ...
    CO2_hist           (Time, Region) float64 ...
    N2O_hist           (Time, Region) float64 ...
    CH4_hist           (Time, Region) float64 ...
    ...                 ...
    Budget             (Temperature, Risk, NonCO2red) float64 ...
    GHG_globe          (NegEmis, NonCO2red, Temperature, Risk, Timing, Time) float64 ...
    CO2_globe          (NegEmis, NonCO2red, Temperature, Risk, Timing, Time) float64 ...
    NonCO2_globe       (NonCO2red, Time, Timing, Temperature) float64 ...
    GHG_base           (Region, Scenario, Time) float64 ...
    GHG_ndc            (Region, Conditionality, Hot_air, Ambition, Time) float64 ...

In [6]:
dataset_old.variables.keys()

KeysView(Frozen({'Scenario': <xarray.IndexVariable 'Scenario' (Scenario: 5)>
array(['SSP1', 'SSP2', 'SSP3', 'SSP4', 'SSP5'], dtype=object), 'Region': <xarray.IndexVariable 'Region' (Region: 207)>
array(['AFG', 'ALB', 'DZA', ..., 'Australasia', 'African Group', 'Umbrella'],
      dtype=object), 'Time': <xarray.IndexVariable 'Time' (Time: 251)>
array([1850, 1851, 1852, ..., 2098, 2099, 2100]), 'Conditionality': <xarray.IndexVariable 'Conditionality' (Conditionality: 3)>
array(['conditional', 'range', 'unconditional'], dtype=object), 'Hot_air': <xarray.IndexVariable 'Hot_air' (Hot_air: 2)>
array(['include', 'exclude'], dtype=object), 'Ambition': <xarray.IndexVariable 'Ambition' (Ambition: 2)>
array(['low', 'high'], dtype=object), 'Temperature': <xarray.IndexVariable 'Temperature' (Temperature: 10)>
array([1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4]), 'Risk': <xarray.IndexVariable 'Risk' (Risk: 5)>
array([0.17, 0.33, 0.5 , 0.67, 0.83]), 'NonCO2red': <xarray.IndexVariable 'NonCO2red' 

In [7]:
dataset_old['GHG_ndc'].to_dataframe().to_csv(r'K:\data\DataUpdate_02_2024\GHG_ndc.csv')

In [8]:
dataset_old

<xarray.Dataset>
Dimensions:            (Scenario: 5, Region: 207, Time: 251, Conditionality: 3,
                        Hot_air: 2, Ambition: 2, Temperature: 10, Risk: 5,
                        NonCO2red: 5, NegEmis: 7, Timing: 2)
Coordinates: (12/14)
  * Scenario           (Scenario) object 'SSP1' 'SSP2' 'SSP3' 'SSP4' 'SSP5'
  * Region             (Region) object 'AFG' 'ALB' ... 'Umbrella'
  * Time               (Time) int32 1850 1851 1852 1853 ... 2097 2098 2099 2100
  * Conditionality     (Conditionality) object 'conditional' ... 'unconditional'
  * Hot_air            (Hot_air) object 'include' 'exclude'
  * Ambition           (Ambition) object 'low' 'high'
    ...                 ...
  * NonCO2red          (NonCO2red) float64 0.1 0.33 0.5 0.67 0.9
  * NegEmis            (NegEmis) float64 0.2 0.3 0.4 0.5 0.6 0.7 0.8
  * Timing             (Timing) object 'Delayed' 'Immediate'
    source             object ...
    Version            object ...
    variable           object ...
Data variables: (12/15)
    GDP                (Scenario, Region, Time) float64 ...
    Population         (Scenario, Region, Time) float64 ...
    GHG_hist           (Time, Region) float64 ...
    CO2_hist           (Time, Region) float64 ...
    N2O_hist           (Time, Region) float64 ...
    CH4_hist           (Time, Region) float64 ...
    ...                 ...
    Budget             (Temperature, Risk, NonCO2red) float64 ...
    GHG_globe          (NegEmis, NonCO2red, Temperature, Risk, Timing, Time) float64 ...
    CO2_globe          (NegEmis, NonCO2red, Temperature, Risk, Timing, Time) float64 ...
    NonCO2_globe       (NonCO2red, Time, Timing, Temperature) float64 ...
    GHG_base           (Region, Scenario, Time) float64 ...
    GHG_ndc            (Region, Conditionality, Hot_air, Ambition, Time) float64 ...

In [9]:
dataset_new

<xarray.Dataset>
Dimensions:         (Scenario: 5, Region: 207, Time: 251, Temperature: 10,
                     Risk: 5, NonCO2red: 5, NegEmis: 7, Timing: 2,
                     Conditionality: 2, Ambition: 2)
Coordinates: (12/13)
  * Scenario        (Scenario) object 'SSP1' 'SSP2' 'SSP3' 'SSP4' 'SSP5'
  * Region          (Region) object 'AFG' 'ALB' ... 'African Group' 'Umbrella'
  * Time            (Time) int32 1850 1851 1852 1853 ... 2097 2098 2099 2100
  * Temperature     (Temperature) float64 1.5 1.6 1.7 1.8 ... 2.1 2.2 2.3 2.4
  * Risk            (Risk) float64 0.17 0.33 0.5 0.67 0.83
  * NonCO2red       (NonCO2red) float64 0.1 0.33 0.5 0.67 0.9
    ...              ...
  * Timing          (Timing) object 'Delayed' 'Immediate'
  * Conditionality  (Conditionality) object 'conditional' 'unconditional'
  * Ambition        (Ambition) object 'max' 'min'
    Version         object ...
    variable        object ...
    source          object ...
Data variables: (12/14)
    GDP             (Scenario, Region, Time) float64 ...
    Population      (Scenario, Region, Time) float64 ...
    GHG_hist        (Time, Region) float64 ...
    CO2_hist        (Time, Region) float64 ...
    N2O_hist        (Time, Region) float64 ...
    CH4_hist        (Time, Region) float64 ...
    ...              ...
    Budget          (Temperature, Risk, NonCO2red) float64 ...
    GHG_globe       (NegEmis, NonCO2red, Temperature, Risk, Timing, Time) float64 ...
    CO2_globe       (NegEmis, NonCO2red, Temperature, Risk, Timing, Time) float64 ...
    NonCO2_globe    (NonCO2red, Time, Timing, Temperature) float64 ...
    GHG_base        (Region, Scenario, Time) float64 ...
    GHG_ndc         (Region, Conditionality, Ambition) float64 ...

In [10]:
dataset_new['GHG_ndc'].to_dataframe().to_csv(r'K:\data\DataUpdate_02_2024\GHG_ndc_new.csv')

## Try out to get NDC range for explorer

In [11]:
# dsGlobal = xr.open_dataset("/data/DataUpdate_02_2024/xr_dataread.nc")
dsGlobal = dataset_old
dsGlobal_new = dataset_new

In [22]:
# Old code for old dataset

def ndcRange(region, period=2030):
    ds = dsGlobal.GHG_ndc.sel(Region=region, Time=period)
    return {period: [ds.min().values.tolist(), ds.max().values.tolist()]}

In [23]:
ndcRange('USA', 2030)

{2030: [3865.926348, 3991.306612]}

In [24]:
# New code for new dataset

def ndcRange_new(region):
    ds = dsGlobal_new.GHG_ndc.sel(Region=region)
    return {2030: [ds.min().values.tolist(), ds.max().values.tolist()]}

In [25]:
ndcRange_new('USA')

{2030: [3214.206596927995, 3348.131871799995]}

## Check new dataread after Mark made changes to LULUCF

In [3]:
dataset_updated_IPCC = xr.open_dataset(r'K:\data\DataUpdate_ongoing\IPCC\xr_dataread.nc')
dataset_updated = xr.open_dataset(r'K:\data\DataUpdate_ongoing\xr_dataread.nc')

In [4]:
dataset_updated

<xarray.Dataset>
Dimensions:         (Scenario: 5, Region: 207, Time: 251, Temperature: 10,
                     Risk: 5, NonCO2red: 5, NegEmis: 7, Timing: 2,
                     Conditionality: 2, Ambition: 2)
Coordinates:
  * Scenario        (Scenario) object 'SSP1' 'SSP2' 'SSP3' 'SSP4' 'SSP5'
  * Region          (Region) object 'AFG' 'ALB' ... 'African Group' 'Umbrella'
  * Time            (Time) int32 1850 1851 1852 1853 ... 2097 2098 2099 2100
  * Temperature     (Temperature) float64 1.5 1.6 1.7 1.8 ... 2.1 2.2 2.3 2.4
  * Risk            (Risk) float64 0.17 0.33 0.5 0.67 0.83
  * NonCO2red       (NonCO2red) float64 0.1 0.33 0.5 0.67 0.9
  * NegEmis         (NegEmis) float64 0.2 0.3 0.4 0.5 0.6 0.7 0.8
  * Timing          (Timing) object 'Delayed' 'Immediate'
  * Conditionality  (Conditionality) object 'conditional' 'unconditional'
  * Ambition        (Ambition) object 'max' 'min'
    variable        object ...
Data variables: (12/13)
    GDP             (Scenario, Region, Time) float64 ...
    Population      (Scenario, Region, Time) float64 ...
    GHG_hist        (Region, Time) float64 ...
    GHG_hist_excl   (Region, Time) float64 ...
    CO2_hist        (Region, Time) float64 ...
    CH4_hist        (Region, Time) float64 ...
    ...              ...
    Budget          (Temperature, Risk, NonCO2red) float64 ...
    GHG_globe       (NegEmis, NonCO2red, Temperature, Risk, Timing, Time) float64 ...
    CO2_globe       (NegEmis, NonCO2red, Temperature, Risk, Timing, Time) float64 ...
    NonCO2_globe    (NonCO2red, Time, Timing, Temperature) float64 ...
    GHG_base        (Region, Scenario, Time) float64 ...
    GHG_ndc         (Region, Conditionality, Ambition) float64 ...

In [5]:
dataset_updated_IPCC

<xarray.Dataset>
Dimensions:         (Scenario: 5, Region: 207, Time: 251, Temperature: 2,
                     Risk: 5, NonCO2red: 5, NegEmis: 7, Timing: 2,
                     Conditionality: 2, Ambition: 2)
Coordinates:
  * Scenario        (Scenario) object 'SSP1' 'SSP2' 'SSP3' 'SSP4' 'SSP5'
  * Region          (Region) object 'AFG' 'ALB' ... 'African Group' 'Umbrella'
  * Time            (Time) int32 1850 1851 1852 1853 ... 2097 2098 2099 2100
  * Temperature     (Temperature) float64 1.56 2.0
  * Risk            (Risk) float64 0.17 0.33 0.5 0.67 0.83
  * NonCO2red       (NonCO2red) float64 0.1 0.33 0.5 0.67 0.9
  * NegEmis         (NegEmis) float64 0.2 0.3 0.4 0.5 0.6 0.7 0.8
  * Timing          (Timing) object 'Delayed' 'Immediate'
  * Conditionality  (Conditionality) object 'conditional' 'unconditional'
  * Ambition        (Ambition) object 'max' 'min'
    variable        object ...
Data variables: (12/13)
    GDP             (Scenario, Region, Time) float64 ...
    Population      (Scenario, Region, Time) float64 ...
    GHG_hist        (Region, Time) float64 ...
    GHG_hist_excl   (Region, Time) float64 ...
    CO2_hist        (Region, Time) float64 ...
    CH4_hist        (Region, Time) float64 ...
    ...              ...
    Budget          (Temperature, Risk, NonCO2red) float64 ...
    GHG_globe       (NegEmis, NonCO2red, Temperature, Risk, Timing, Time) float64 ...
    CO2_globe       (NegEmis, NonCO2red, Temperature, Risk, Timing, Time) float64 ...
    NonCO2_globe    (NonCO2red, Time, Timing, Temperature) float64 ...
    GHG_base        (Region, Scenario, Time) float64 ...
    GHG_ndc         (Region, Conditionality, Ambition) float64 ...